name: Create release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v1

      - name: Set up NuGet CLI
        run: Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile C:\Windows\nuget.exe

      - name: Install packages
        run: nuget restore .\MouseTester\MouseTester.sln

      - name: Build executable
        run: |
          MSBuild.exe .\MouseTester\MouseTester.sln -p:Configuration=Release -p:Platform=x64

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: ./MouseTester/MouseTester/bin/x64/Release/MouseTester.exe
