name: Create release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v1

      - name: Install packages
        run: nuget restore .\MouseTester\MouseTester.sln

      - name: Build executable
        run: |
          MSBuild.exe .\MouseTester\MouseTester.sln -p:Configuration=Release -p:Platform=x64

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./MouseTester/MouseTester/bin/x64/Release/MouseTester.exe
